theme: jekyll-theme-cayman
title: Learn beginner's French
description: An introduction to the French language and helping with travels to France 
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: page6.html
