theme: jekyll-theme-cayman
title: <img src="https://lh3.googleusercontent.com/Ti5lHLDttEfPBl7QtLAh2AtJn8LKFvFZS46pTnCV4FuRrp-RTneS74TTtTCA2rBoBG7QZ5ovXoaPQUZQxGp6OiE8lVhZ-5F9rAnrelj9pOaaV5JKpmdh-6PGHPH35lt6znxbpXDuNA=w2400" alt= "logo" height="100" width= "175"
description: <strong> An introduction to the French language and helping with travels to France </strong> 
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: page6.html
