theme: jekyll-theme-cayman
title: <img src="https://lh3.googleusercontent.com/6YD0zyhoGsxyLcPUsh7hfqE8seiPtd0eQa5S8hI-ebwZnc4RgYEHy3v-ARqhbfVb9jfySXDCM8tL2EBzPn5GiFx04Pw028rqvB0CDZzICY1htyYX4XNcb2KKzpadiuKApC-2JKl8jw=w2400" alt= "logo" height="150" width= "225"
description: <strong> An introduction to the French language and helping with travels to France </strong> 
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: page6.html
