theme: jekyll-theme-cayman
title: <img src="https://lh3.googleusercontent.com/fhc0duhCHPhbACjJQhZ8POcSb-jKz0F71wTaLfLMcKY8WS9cdAph4cdFuWss3yclxhAJupQr25pqaIrC02GfZj49SqQItNsapGir6CCyeiUIcmagrZJD0sOLHmW_z3DruflcEudcjw=w2400" alt= "logo" height="100" width= "175"
description: <strong> An introduction to the French language and helping with travels to France </strong> 
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: page6.html
